const launch = (url: string, label: string) => `<a class="idea-launch" href="${url}" target="_blank" rel="noopener noreferrer">${label}<span aria-hidden="true">↗</span></a>`;

export function renderIdeas() {
  return `<article class="idea-lab">
    <header class="idea-lab-header"><div><span class="idea-eyebrow">OPEN THE BIN. FIND SOMETHING GOOD.</span><h2>Bin of Ideas<span aria-hidden="true">✳</span></h2><p>A little room for curiosity. Working demos, side experiments and ideas worth taking for a spin.</p></div><span class="idea-count" aria-label="3 ideas">03<small>KEPT, NOT DELETED</small></span></header>
    <div class="idea-cards">
      <article class="idea-card idea-training"><div class="idea-art"><span class="idea-index">01 / LEARN</span><img src="/work/legrand-avatar.webp" alt="Legrand agentic training experience interface"/><span class="idea-sticker">Ask. Explore. Learn.</span></div><div class="idea-card-body"><span class="idea-type">INTERACTIVE DEMO</span><h3>Legrand Training Experience</h3><p>Product knowledge becomes a conversation. Explore the agentic training experience and discover Legrand products through an AI guide.</p>${launch("https://ai.xfactorz.evolutionco.in/", "Open training experience")}</div></article>
      <article class="idea-card idea-theatre"><div class="idea-art cinema-art"><span class="idea-index">02 / EXPERIENCE</span><div class="cinema-ticket" aria-hidden="true"><span>PVR INOX</span><strong>BEYOND<br/>THE SCREEN.</strong><span class="ticket-bottom">ADMIT ONE · AI EXPERIENCE <b>✳</b></span></div><span class="idea-sticker">Roll the conversation.</span></div><div class="idea-card-body"><span class="idea-type">INTERACTIVE DEMO · SIGN-IN REQUIRED</span><h3>Theatre Experience</h3><p>A cinema concierge for conversations about films and actors. Explore the PVR INOX experience powered by Xfactorz.</p>${launch("https://ai.theatre.evolutionco.co.in/", "Open theatre experience")}</div></article>
      <article class="idea-card idea-physio"><div class="idea-art"><span class="idea-index">03 / EXPLORE</span><img src="/work/covers/physio.webp" alt="PhysioByRutvi home-care website presentation"/><span class="idea-sticker">Care starts with clarity.</span></div><div class="idea-card-body"><span class="idea-type">DIGITAL EXPERIMENT</span><h3>PhysioByRutvi</h3><p>An exploration of how a digital service can make finding home physiotherapy feel simpler, warmer and more approachable.</p><div class="idea-actions">${launch("https://physiobyrutvi.in/", "Visit the website")}<button class="idea-note" data-open="physio">Read the idea →</button></div></div></article>
    </div><footer class="idea-lab-footer"><span>Curiosity has a home here.</span><button data-open="work">Back to selected work ↗</button></footer>
  </article>`;
}
